package SC2002.Project;

import java.util.Date;
import java.util.Scanner;

/**
 * Represents a report generated by an HDB Manager.
 */
public class Report {
    private static int counter = 1;
    private int reportID;
    private Date generatedDate;
    private String content;

    public Report(String sc) {
        this.reportID = counter++;
        this.generatedDate = new Date();
        this.content = sc;
    }

    public void printReport() {
        System.out.println("Report ID: " + reportID);
        System.out.println("Generated on: " + generatedDate);
        System.out.println(content);
    }
}
