package SC2002.Project.entity;

import java.util.Date;

/**
 * Represents a report generated by an HDB Manager.
 */
public class Report {
    private static int counter = 1;
    private int reportID;
    private Date generatedDate;
    private String content;
    
    public Report(String content) {
        this.reportID = counter++;
        this.generatedDate = new Date();
        this.content = content;
    }
    
    public void printReport() {
        System.out.println("Report ID: " + reportID);
        System.out.println("Generated on: " + generatedDate);
        System.out.println(content);
    }
}
